/*global G */



var Assets = {

        map:  [
          //|0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6
          //|- - - - - - - - - - - - -|x|- - - - - - - - - - - - -|
            [1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1],// 0
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 1
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 2
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 3
            [1,0,0,0,0,0,0,0,0,2,1,1,1,1,1,1,1,3,0,0,0,0,0,0,0,0,1],// 4
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 5
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 6
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 7
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 8
            [1,1,1,1,1,1,1,1,1,3,0,0,0,0,0,0,0,2,1,1,1,1,1,1,1,1,1],// 9
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 10
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 11
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 12
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 13
            [1,0,0,0,0,0,0,0,0,2,1,1,1,1,1,1,1,3,0,0,0,0,0,0,0,0,1],// 14
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 15
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 16
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],// 17
            [1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1],// 18
            [1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1] // 19
          //|- - - - - - - - - - - - -|x|- - - - - - - - - - - - -|


        ],

        sounds: {
            jump: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 2,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 0,
                "osc2_xenv": 1,
                "osc2_vol": 201,
                "osc2_waveform": 0,
                "noise_fader": 0,
                "env_attack": 7105,
                "env_sustain": 150,
                "env_release": 0,
                "env_master": 191,
                "fx_filter": 2,
                "fx_freq": 5839,
                "fx_resonance": 254,
                "fx_delay_time": 1,
                "fx_delay_amt": 16,
                "fx_pan_freq": 6,
                "fx_pan_amt": 128,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 1,
                "lfo_freq": 6,
                "lfo_amt": 195,
                "lfo_waveform": 0
            },

            shoot: {
                "osc1_oct": 7,
                "osc1_det": 1,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 1,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 64,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 2,
                "noise_fader": 27,
                "env_attack": 0,
                "env_sustain": 351,
                "env_release": 7916,
                "env_master": 135,
                "fx_filter": 0,
                "fx_freq": 11025,
                "fx_resonance": 255,
                "fx_delay_time": 1,
                "fx_delay_amt": 41,
                "fx_pan_freq": 0,
                "fx_pan_amt": 0,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 0,
                "lfo_amt": 0,
                "lfo_waveform": 0
            },

            boom: {
                "osc1_oct": 7,
                "osc1_det": 1,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 3,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 64,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 2,
                "noise_fader": 115,
                "env_attack": 0,
                "env_sustain": 663,
                "env_release": 21074,
                "env_master": 135,
                "fx_filter": 0,
                "fx_freq": 11025,
                "fx_resonance": 255,
                "fx_delay_time": 1,
                "fx_delay_amt": 91,
                "fx_pan_freq": 0,
                "fx_pan_amt": 0,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 0,
                "lfo_amt": 0,
                "lfo_waveform": 0
            },

            sizzle: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 2,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 0,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 3,
                "noise_fader": 159,
                "env_attack": 927,
                "env_sustain": 2418,
                "env_release": 16584,
                "env_master": 172,
                "fx_filter": 3,
                "fx_freq": 11025,
                "fx_resonance": 198,
                "fx_delay_time": 0,
                "fx_delay_amt": 0,
                "fx_pan_freq": 0,
                "fx_pan_amt": 0,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 0,
                "lfo_amt": 0,
                "lfo_waveform": 0
            }

        },

        song: {
            "rowLen": 2756,
            "endPattern": 21,
            "songData": [
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 255,
                    "osc1_waveform": 0,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 1,
                    "osc2_vol": 255,
                    "osc2_waveform": 0,
                    "noise_fader": 0,
                    "env_attack": 50,
                    "env_sustain": 150,
                    "env_release": 4800,
                    "env_master": 88,
                    "fx_filter": 2,
                    "fx_freq": 600,
                    "fx_resonance": 128,
                    "fx_delay_time": 0,
                    "fx_delay_amt": 0,
                    "fx_pan_freq": 0,
                    "fx_pan_amt": 0,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 82,
                    "osc1_waveform": 2,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 0,
                    "osc2_waveform": 0,
                    "noise_fader": 255,
                    "env_attack": 100,
                    "env_sustain": 0,
                    "env_release": 1776,
                    "env_master": 111,
                    "fx_filter": 3,
                    "fx_freq": 5200,
                    "fx_resonance": 63,
                    "fx_delay_time": 0,
                    "fx_delay_amt": 0,
                    "fx_pan_freq": 0,
                    "fx_pan_amt": 0,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                0,
                                0,
                                152,
                                0,
                                152,
                                0,
                                152,
                                0,
                                0,
                                0,
                                152,
                                0,
                                152,
                                0,
                                152,
                                0,
                                0,
                                0,
                                152,
                                0,
                                152,
                                0,
                                152,
                                0,
                                0,
                                0,
                                152,
                                0,
                                152,
                                0,
                                152,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 1,
                    "osc2_oct": 6,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 0,
                    "env_sustain": 2000,
                    "env_release": 2653,
                    "env_master": 166,
                    "fx_filter": 2,
                    "fx_freq": 982,
                    "fx_resonance": 89,
                    "fx_delay_time": 2,
                    "fx_delay_amt": 25,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 61,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 3,
                    "lfo_amt": 69,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        2,
                        3,
                        4,
                        1,
                        2,
                        3,
                        4,
                        1,
                        2,
                        3,
                        4,
                        1,
                        2,
                        3,
                        4,
                        1,
                        2,
                        3,
                        4
                    ],
                    "c": [
                        {
                            "n": [
                                135,
                                0,
                                0,
                                0,
                                0,
                                0,
                                135,
                                0,
                                0,
                                0,
                                0,
                                0,
                                135,
                                0,
                                0,
                                0,
                                0,
                                0,
                                135,
                                0,
                                0,
                                0,
                                0,
                                0,
                                140,
                                0,
                                0,
                                0,
                                139,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                133,
                                0,
                                0,
                                0,
                                0,
                                0,
                                133,
                                0,
                                0,
                                0,
                                0,
                                0,
                                133,
                                0,
                                0,
                                0,
                                0,
                                0,
                                133,
                                0,
                                0,
                                0,
                                0,
                                0,
                                140,
                                0,
                                0,
                                0,
                                139,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                132,
                                0,
                                0,
                                0,
                                0,
                                0,
                                132,
                                0,
                                0,
                                0,
                                0,
                                0,
                                132,
                                0,
                                0,
                                0,
                                0,
                                0,
                                132,
                                0,
                                0,
                                0,
                                0,
                                0,
                                140,
                                0,
                                0,
                                0,
                                139,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                131,
                                0,
                                0,
                                0,
                                0,
                                0,
                                131,
                                0,
                                0,
                                0,
                                0,
                                0,
                                131,
                                0,
                                0,
                                0,
                                0,
                                0,
                                131,
                                0,
                                0,
                                0,
                                0,
                                0,
                                133,
                                0,
                                0,
                                0,
                                130,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 160,
                    "osc1_waveform": 0,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 1,
                    "osc2_vol": 160,
                    "osc2_waveform": 0,
                    "noise_fader": 210,
                    "env_attack": 50,
                    "env_sustain": 200,
                    "env_release": 1403,
                    "env_master": 79,
                    "fx_filter": 4,
                    "fx_freq": 11025,
                    "fx_resonance": 254,
                    "fx_delay_time": 1,
                    "fx_delay_amt": 32,
                    "fx_pan_freq": 5,
                    "fx_pan_amt": 61,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 4,
                    "lfo_amt": 60,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                }
            ],
            "songLen": 42
        },

        titlesong: {
            "rowLen": 6963,
            "endPattern": 5,
            "songData": [
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 2,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 13,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 3,
                    "noise_fader": 0,
                    "env_attack": 0,
                    "env_sustain": 5614,
                    "env_release": 0,
                    "env_master": 28,
                    "fx_filter": 0,
                    "fx_freq": 11025,
                    "fx_resonance": 255,
                    "fx_delay_time": 0,
                    "fx_delay_amt": 0,
                    "fx_pan_freq": 1,
                    "fx_pan_amt": 60,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 8,
                    "lfo_amt": 191,
                    "lfo_waveform": 2,
                    "p": [
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                123,
                                0,
                                0,
                                123,
                                0,
                                0,
                                123,
                                123,
                                123,
                                121,
                                0,
                                121,
                                0,
                                0,
                                121,
                                121,
                                121,
                                120,
                                0,
                                120,
                                0,
                                0,
                                120,
                                120,
                                119,
                                0,
                                0,
                                118,
                                0,
                                0,
                                114,
                                113
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 255,
                    "osc1_waveform": 0,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 1,
                    "osc2_vol": 255,
                    "osc2_waveform": 0,
                    "noise_fader": 29,
                    "env_attack": 50,
                    "env_sustain": 150,
                    "env_release": 4800,
                    "env_master": 195,
                    "fx_filter": 2,
                    "fx_freq": 600,
                    "fx_resonance": 192,
                    "fx_delay_time": 1,
                    "fx_delay_amt": 0,
                    "fx_pan_freq": 0,
                    "fx_pan_amt": 0,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 2,
                    "p": [
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 82,
                    "osc1_waveform": 2,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 0,
                    "osc2_waveform": 0,
                    "noise_fader": 255,
                    "env_attack": 100,
                    "env_sustain": 0,
                    "env_release": 1234,
                    "env_master": 186,
                    "fx_filter": 3,
                    "fx_freq": 10121,
                    "fx_resonance": 64,
                    "fx_delay_time": 0,
                    "fx_delay_amt": 24,
                    "fx_pan_freq": 0,
                    "fx_pan_amt": 0,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123,
                                0,
                                123,
                                123,
                                123
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 1,
                    "osc2_oct": 6,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 137,
                    "env_sustain": 2000,
                    "env_release": 4611,
                    "env_master": 124,
                    "fx_filter": 1,
                    "fx_freq": 982,
                    "fx_resonance": 89,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 25,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 77,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 4,
                    "lfo_amt": 163,
                    "lfo_waveform": 3,
                    "p": [
                        1,
                        2,
                        1,
                        2
                    ],
                    "c": [
                        {
                            "n": [
                                159,
                                154,
                                159,
                                162,
                                0,
                                161,
                                159,
                                157,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                159,
                                157,
                                156,
                                152,
                                156,
                                162,
                                0,
                                161,
                                159,
                                161,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                166,
                                164,
                                162,
                                159,
                                0,
                                154,
                                162,
                                159,
                                161,
                                157,
                                154,
                                0,
                                0,
                                154,
                                159,
                                154,
                                155,
                                154,
                                152,
                                147,
                                0,
                                149,
                                150,
                                149,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 221,
                    "osc1_waveform": 3,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 1,
                    "osc2_vol": 210,
                    "osc2_waveform": 3,
                    "noise_fader": 255,
                    "env_attack": 50,
                    "env_sustain": 150,
                    "env_release": 7505,
                    "env_master": 127,
                    "fx_filter": 3,
                    "fx_freq": 7355,
                    "fx_resonance": 206,
                    "fx_delay_time": 2,
                    "fx_delay_amt": 24,
                    "fx_pan_freq": 1,
                    "fx_pan_amt": 142,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 7,
                    "lfo_amt": 64,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                0,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                123,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 3,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 160,
                    "osc2_waveform": 0,
                    "noise_fader": 0,
                    "env_attack": 100,
                    "env_sustain": 150,
                    "env_release": 13636,
                    "env_master": 59,
                    "fx_filter": 2,
                    "fx_freq": 5839,
                    "fx_resonance": 254,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 28,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 147,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 4,
                    "lfo_amt": 195,
                    "lfo_waveform": 3,
                    "p": [
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                142,
                                138,
                                142,
                                138,
                                142,
                                138,
                                142,
                                138,
                                140,
                                137,
                                140,
                                137,
                                140,
                                137,
                                140,
                                137,
                                138,
                                135,
                                138,
                                135,
                                138,
                                135,
                                138,
                                135,
                                137,
                                134,
                                137,
                                134,
                                137,
                                134,
                                137,
                                134
                            ]
                        }
                    ]
                }
            ],
            "songLen": 27
        },

        gameover: {
            "rowLen": 2756,
            "endPattern": 2,
            "songData": [
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 170,
                    "osc1_waveform": 1,
                    "osc2_oct": 5,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 0,
                    "osc2_waveform": 3,
                    "noise_fader": 0,
                    "env_attack": 100,
                    "env_sustain": 0,
                    "env_release": 2193,
                    "env_master": 232,
                    "fx_filter": 2,
                    "fx_freq": 559,
                    "fx_resonance": 135,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 117,
                    "fx_pan_freq": 0,
                    "fx_pan_amt": 0,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                137,
                                140,
                                144,
                                149,
                                132,
                                137,
                                140,
                                145,
                                128,
                                131,
                                135,
                                140,
                                123,
                                126,
                                130,
                                135,
                                118,
                                121,
                                125,
                                130,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                }
            ],
            "songLen": 4
        },

        glitchget: {
            "rowLen": 2756,
            "endPattern": 2,
            "songData": [
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 1,
                    "osc2_oct": 6,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 137,
                    "env_sustain": 2000,
                    "env_release": 4611,
                    "env_master": 192,
                    "fx_filter": 1,
                    "fx_freq": 982,
                    "fx_resonance": 89,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 25,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 77,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 3,
                    "lfo_amt": 69,
                    "lfo_waveform": 0,
                    "p": [
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                151,
                                154,
                                159,
                                152,
                                156,
                                159,
                                164,
                                154,
                                158,
                                161,
                                166,
                                173,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                }
            ],
            "songLen": 4
        },

        letters: {
            '.' : [
                [,,,,0],
                [,,,,0],
                [,,,,0],
                [,,,,0],
                [,,1,,0]

            ],
            '1': [
                [,1,1,,0],
                [,,1,,0],
                [,,1,,0],
                [,,1,,0],
                [1,1,1,1,1]

            ],
            '2': [
                [1, 1, 1, 1, 0],
                [, , , , 1],
                [, 1, 1, 1, 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            '3': [
                [1, 1, 1, 1, 0],
                [, , , , 1],
                [, 1, 1, 1, 1],
                [, , , , 1],
                [1, 1, 1, 1, 0]
            ],
            '4': [
                [1, , , 1, 0],
                [1, , , 1, 0],
                [1, 1, 1, 1, 1],
                [, , , 1, 0],
                [, , , 1, 0]
            ],
            '5': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, 1, 0],
                [, , , , 1],
                [1, 1, 1, 1, 0]
            ],
            '6': [
                [, 1, 1, 1, 0],
                [1, , , , 0],
                [1, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 0]
            ],
            '7': [
                [1, 1, 1, 1, 1],
                [, , , , 1],
                [, , , 1, 0],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            '8': [
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 0]
            ],
            '9': [
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 1],
                [, , , , 1],
                [, 1, 1, 1, 0]
            ],
            '0': [
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [, 1, 1, 1, 0]
            ],
            'A': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , , , 1]
            ],
            'B': [
                [1, 1, 1, 1, 0],
                [1, , , 1, 0],
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'C': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, , , , 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            'D': [
                [1, 1, 1, , 0],
                [1, , , 1, 0],
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'E': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, , 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            'F': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, , 0],
                [1, , , , 0],
                [1, , , , 0]
            ],
            'G': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, , 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'H': [
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , , , 1]
            ],
            'I': [
                [1, 1, 1, 1, 1],
                [, , 1, , 0],
                [, , 1, , 0],
                [, , 1, , 0],
                [1, 1, 1, 1, 1]
            ],
            'J': [
                [, , , , 1],
                [, , , , 1],
                [, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'K': [
                [1, , , 1, 0],
                [1, , 1, , 0],
                [1, 1, 1, , 0],
                [1, , , 1, 0],
                [1, , , , 1]
            ],
            'L': [
                [1, , , , 0],
                [1, , , , 0],
                [1, , , , 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            'M': [
                [1, , , , 1],
                [1, 1, , 1, 1],
                [1, , 1, , 1],
                [1, , , , 1],
                [1, , , , 1]
            ],
            'N': [
                [1, , , , 1],
                [1, 1, , , 1],
                [1, , 1, , 1],
                [1, , , 1, 1],
                [1, , , , 1]
            ],
            'O': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'P': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, , , , 0]
            ],
            'Q': [
                [1, 1, 1, 1, 0],
                [1, , , 1, 0],
                [1, , , 1, 0],
                [1, , , 1, 0],
                [1, 1, 1, 1, 1]
            ],
            'R': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , 1, 0],
                [1, , , , 1]
            ],
            'S': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, 1, 1],
                [, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'T': [
                [1, 1, 1, 1, 1],
                [, , 1, , 0],
                [, , 1, , 0],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            'U': [
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'V': [
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [, 1, , 1, 0],
                [, , 1, , 0]
            ],
            'W': [
                [1, , , , 1],
                [1, , , , 1],
                [1, , 1, , 1],
                [1, 1, , 1, 1],
                [1, , , , 1]
            ],
            'X': [
                [1, , , , 1],
                [, 1, , 1, 0],
                [, , 1, , 0],
                [, 1, , 1, 0],
                [1, , , , 1]
            ],
            'Y': [
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            'Z': [
                [1, 1, 1, 1, 1],
                [, , , 1, 0],
                [, , 1, , 0],
                [, 1, , , 0],
                [1, 1, 1, 1, 1]
            ],
            ' ': [
                [, , , , 0],
                [, , , , 0],
                [, , , , 0],
                [, , , , 0],
                [, , , , 0]
            ],
            ',': [
                [, , , , 0],
                [, , , , 0],
                [, , , , 0],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            '+': [
                [, , , , 0],
                [, , 1, , 0],
                [, 1, 1, 1, 0],
                [, , 1, , 0],
                [, , , , 0]
            ],
            '/': [
                [, , , , 1],
                [, , , 1, 0],
                [, , 1, , 0],
                [, 1, , , 0],
                [1, , , , 0]
            ],
            ':': [
                [, , , , 0],
                [, , 1, , 0],
                [, , , , 0],
                [, , 1, , 0],
                [, , , , 0]
            ],
            '@': [
                [1, 1, 1, 1, 1],
                [, , , , 1],
                [1, 1, 1, , 1],
                [1, , 1, , 1],
                [1, 1, 1, 1, 1]
            ],
            'x': [ //solid first checkers
                [1, , 1, , 1],
                [, 1, , 1, 0],
                [1, , 1, , 1],
                [, 1, , 1, 0],
                [1, , 1, , 1]
            ],
            'z': [
                //empty first checkers
                [, 1, , 1, 0],
                [1, , 1, , 1],
                [, 1, , 1, 0],
                [1, , 1, , 1],
                [, 1, , 1, 0]
            ],
            'o': [
                //box with dot
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , 1, , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'e': [
                //down-right slope
                [1,,,,0],
                [1,1,,,0],
                [1,1,1,,0],
                [1,1,1,1,0],
                [1,1,1,1,1],

            ],
            'w': [
                //down-left slope
                [,,,,1],
                [,,,1,1],
                [,,1,1,1],
                [,1,1,1,1],
                [1,1,1,1,1],

            ],
            's': [
                //up-left slope
                [1, 1, 1, 1, 1],
                [, 1, 1, 1, 1],
                [, , 1, 1, 1],
                [, , , 1, 1],
                [, , , , 1]
            ],
            'd': [
                //up-right slope
                [1,1,1,1,1],
                [1,1,1,1,0],
                [1,1,1,,0],
                [1,1,,,0],
                [1,,,,0]

            ],
            't': [
                //player 1
                [0,0,0,1,1],
                [0,0,1,1,1],
                [0,0,1,1,1],
                [0,0,1,1,1],
                [0,0,1,1,1],

            ],
            'y': [
                //player 1
                [1,1,1,1,1],
                [1,1,1,1,1],
                [1,1,1,1,1],
                [1,1,1,1,1],
                [1,1,1,1,1]
            ],
            'u': [
                //player 1
                [1,1,0,0,0],
                [1,1,1,0,0],
                [0,0,1,0,0],
                [0,1,1,0,0],
                [1,1,1,0,0]
            ],
            'g': [
                //player 1
                [0,0,1,1,1],
                [0,0,0,1,1],
                [0,0,0,0,0],
                [0,0,0,0,0],
                [0,0,0,0,1]
            ],
            'h': [
                //player 1
                [1,1,1,1,1],
                [1,1,1,1,1],
                [0,1,1,1,0],
                [1,1,1,1,1],
                [1,1,1,1,1]
            ],
            'j': [
                //player 1
                [1,1,1,0,0],
                [1,1,0,0,0],
                [0,0,0,0,0],
                [0,0,0,0,0],
                [1,1,1,1,1]
            ],
            'b': [
                //player 1
                [0,0,0,1,1],
                [0,0,0,1,1],
                [0,0,0,0,1],
                [0,0,0,0,1],
                [0,0,0,0,1]
            ],
            'n': [
                //player 1
                [1,1,1,1,1],
                [1,1,1,1,1],
                [0,0,0,0,0],
                [0,0,0,0,0],
                [0,0,0,0,0],

            ],
            'm': [
                //player 1
                [1,1,1,1,1],
                [1,0,0,1,1],
                [1,0,0,0,0],
                [1,0,0,0,0],
                [1,0,0,0,0]
            ],

        }

    };