/*global G */

//sounds created in sonant-live composer, rendered with sonant-x
//5x5 pixel letters created by Jack Rugile, Radius Raid
//5x5 sprite-part lowercase characters graphics created by Ryan Malm

(function(g){


//todo: letters-sprites: investigate hand-compression schemes, RLE, encoding each sprite as a single integer
    g.Assets = {

        map:  [

            [1,1,1,1,1,1,1,1,,,,,1,1,1,1,1,1,1,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,1,1,1,1,1,1,1,1,1,1,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,1,1,1,1,,,,,,,,,,,1,1,1,1,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,,,,,,,,,,,,,,,,,,,1],
            [1,1,1,1,1,1,1,1,,,,,1,1,1,1,1,1,1,1],

        ],

        sounds: {
            jump: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 2,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 0,
                "osc2_xenv": 1,
                "osc2_vol": 201,
                "osc2_waveform": 0,
                "noise_fader": 0,
                "env_attack": 7105,
                "env_sustain": 150,
                "env_release": 0,
                "env_master": 191,
                "fx_filter": 2,
                "fx_freq": 5839,
                "fx_resonance": 254,
                "fx_delay_time": 1,
                "fx_delay_amt": 16,
                "fx_pan_freq": 6,
                "fx_pan_amt": 128,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 1,
                "lfo_freq": 6,
                "lfo_amt": 195,
                "lfo_waveform": 0
            },

            engineSound2: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 0,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 39,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 0,
                "noise_fader": 0,
                "env_attack": 193767,
                "env_sustain": 118467,
                "env_release": 200000,
                "env_master": 192,
                "fx_filter": 4,
                "fx_freq": 2962,
                "fx_resonance": 143,
                "fx_delay_time": 1,
                "fx_delay_amt": 35,
                "fx_pan_freq": 1,
                "fx_pan_amt": 255,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 3,
                "lfo_amt": 0,
                "lfo_waveform": 1
            },

            engineSound3: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 0,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 39,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 0,
                "noise_fader": 0,
                "env_attack": 193767,
                "env_sustain": 118467,
                "env_release": 200000,
                "env_master": 192,
                "fx_filter": 4,
                "fx_freq": 2962,
                "fx_resonance": 143,
                "fx_delay_time": 1,
                "fx_delay_amt": 35,
                "fx_pan_freq": 1,
                "fx_pan_amt": 255,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 3,
                "lfo_amt": 0,
                "lfo_waveform": 1
            },

            engineSound4: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 0,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 39,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 0,
                "noise_fader": 0,
                "env_attack": 193767,
                "env_sustain": 118467,
                "env_release": 200000,
                "env_master": 192,
                "fx_filter": 4,
                "fx_freq": 2962,
                "fx_resonance": 143,
                "fx_delay_time": 1,
                "fx_delay_amt": 35,
                "fx_pan_freq": 1,
                "fx_pan_amt": 255,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 3,
                "lfo_amt": 0,
                "lfo_waveform": 1
            },
            engineSound5: {
                "osc1_oct": 7,
                "osc1_det": 0,
                "osc1_detune": 0,
                "osc1_xenv": 1,
                "osc1_vol": 192,
                "osc1_waveform": 0,
                "osc2_oct": 7,
                "osc2_det": 0,
                "osc2_detune": 39,
                "osc2_xenv": 1,
                "osc2_vol": 192,
                "osc2_waveform": 0,
                "noise_fader": 0,
                "env_attack": 193767,
                "env_sustain": 118467,
                "env_release": 200000,
                "env_master": 192,
                "fx_filter": 4,
                "fx_freq": 2962,
                "fx_resonance": 143,
                "fx_delay_time": 1,
                "fx_delay_amt": 35,
                "fx_pan_freq": 1,
                "fx_pan_amt": 255,
                "lfo_osc1_freq": 0,
                "lfo_fx_freq": 0,
                "lfo_freq": 3,
                "lfo_amt": 0,
                "lfo_waveform": 1
            }

        },

        song: {
            "songLen": 36,
            "songData": [
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 234,
                    "osc1_waveform": 1,
                    "osc2_oct": 6,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 219,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 137,
                    "env_sustain": 2000,
                    "env_release": 4611,
                    "env_master": 255,
                    "fx_filter": 4,
                    "fx_freq": 982,
                    "fx_resonance": 89,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 25,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 77,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 4,
                    "lfo_amt": 152,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1,
                        2,
                        1,
                        1,
                        2,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                123,
                                0,
                                123,
                                0,
                                126,
                                0,
                                126,
                                0,
                                128,
                                0,
                                128,
                                0,
                                0,
                                0,
                                0,
                                0,
                                123,
                                0,
                                123,
                                0,
                                126,
                                0,
                                126,
                                0,
                                128,
                                0,
                                128,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                125,
                                0,
                                125,
                                0,
                                128,
                                0,
                                128,
                                0,
                                130,
                                0,
                                130,
                                0,
                                0,
                                0,
                                0,
                                0,
                                125,
                                0,
                                125,
                                0,
                                128,
                                0,
                                128,
                                0,
                                130,
                                0,
                                130,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 255,
                    "osc1_waveform": 2,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 154,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 197,
                    "env_sustain": 2193,
                    "env_release": 351,
                    "env_master": 184,
                    "fx_filter": 0,
                    "fx_freq": 11025,
                    "fx_resonance": 255,
                    "fx_delay_time": 4,
                    "fx_delay_amt": 108,
                    "fx_pan_freq": 3,
                    "fx_pan_amt": 56,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1,
                        2,
                        1,
                        1,
                        2
                    ],
                    "c": [
                        {
                            "n": [
                                135,
                                0,
                                0,
                                0,
                                138,
                                0,
                                0,
                                0,
                                140,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                150,
                                0,
                                0,
                                0,
                                152,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                137,
                                0,
                                0,
                                0,
                                140,
                                0,
                                0,
                                0,
                                142,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                149,
                                0,
                                0,
                                0,
                                152,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 1,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 11,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 3,
                    "noise_fader": 29,
                    "env_attack": 88,
                    "env_sustain": 548,
                    "env_release": 1584,
                    "env_master": 228,
                    "fx_filter": 0,
                    "fx_freq": 11025,
                    "fx_resonance": 255,
                    "fx_delay_time": 4,
                    "fx_delay_amt": 134,
                    "fx_pan_freq": 7,
                    "fx_pan_amt": 156,
                    "lfo_osc1_freq": 1,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        2,
                        1,
                        2,
                        3,
                        2,
                        1,
                        3,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                123,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                154,
                                0,
                                159,
                                0,
                                166,
                                0,
                                171,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                171,
                                0,
                                166,
                                0,
                                159,
                                0,
                                154,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                125,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                149,
                                0,
                                156,
                                0,
                                161,
                                0,
                                168,
                                0,
                                173,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 113,
                    "osc1_waveform": 3,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 0,
                    "osc2_waveform": 0,
                    "noise_fader": 247,
                    "env_attack": 41496,
                    "env_sustain": 26863,
                    "env_release": 91231,
                    "env_master": 138,
                    "fx_filter": 3,
                    "fx_freq": 7640,
                    "fx_resonance": 188,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 124,
                    "fx_pan_freq": 2,
                    "fx_pan_amt": 115,
                    "lfo_osc1_freq": 1,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 5,
                    "lfo_amt": 232,
                    "lfo_waveform": 2,
                    "p": [
                        0,
                        1,
                        0,
                        1,
                        0,
                        1,
                        0,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 1,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 49,
                    "env_sustain": 3426,
                    "env_release": 49,
                    "env_master": 192,
                    "fx_filter": 1,
                    "fx_freq": 982,
                    "fx_resonance": 140,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 25,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 77,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 3,
                    "lfo_amt": 69,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        1,
                        1,
                        2,
                        1,
                        1,
                        2
                    ],
                    "c": [
                        {
                            "n": [
                                123,
                                123,
                                135,
                                135,
                                126,
                                126,
                                138,
                                138,
                                128,
                                128,
                                140,
                                140,
                                133,
                                133,
                                145,
                                145,
                                123,
                                123,
                                135,
                                135,
                                126,
                                126,
                                138,
                                138,
                                128,
                                128,
                                140,
                                140,
                                130,
                                130,
                                142,
                                142
                            ]
                        },
                        {
                            "n": [
                                125,
                                125,
                                137,
                                137,
                                128,
                                128,
                                140,
                                140,
                                130,
                                130,
                                142,
                                142,
                                135,
                                135,
                                147,
                                147,
                                125,
                                125,
                                137,
                                137,
                                128,
                                128,
                                140,
                                140,
                                130,
                                130,
                                142,
                                142,
                                132,
                                132,
                                144,
                                144
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 5,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 214,
                    "osc1_waveform": 0,
                    "osc2_oct": 5,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 1,
                    "osc2_vol": 204,
                    "osc2_waveform": 0,
                    "noise_fader": 229,
                    "env_attack": 50,
                    "env_sustain": 6363,
                    "env_release": 1818,
                    "env_master": 158,
                    "fx_filter": 3,
                    "fx_freq": 7924,
                    "fx_resonance": 240,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 74,
                    "fx_pan_freq": 4,
                    "fx_pan_amt": 232,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 6,
                    "lfo_amt": 231,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                147,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 3,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 4,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 3,
                    "noise_fader": 0,
                    "env_attack": 36863,
                    "env_sustain": 35969,
                    "env_release": 8772,
                    "env_master": 192,
                    "fx_filter": 1,
                    "fx_freq": 3022,
                    "fx_resonance": 255,
                    "fx_delay_time": 4,
                    "fx_delay_amt": 140,
                    "fx_pan_freq": 3,
                    "fx_pan_amt": 162,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 8,
                    "lfo_amt": 255,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        1,
                        2,
                        3
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                149,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                156,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                168,
                                0,
                                161,
                                0,
                                152,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                171,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                }
            ],
            "rowLen": 4410,
            "endPattern": 11
        },

        titlesong: {
            "songLen": 37,
            "songData": [
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 3,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 7,
                    "osc2_xenv": 0,
                    "osc2_vol": 201,
                    "osc2_waveform": 3,
                    "noise_fader": 0,
                    "env_attack": 789,
                    "env_sustain": 1234,
                    "env_release": 13636,
                    "env_master": 191,
                    "fx_filter": 2,
                    "fx_freq": 5839,
                    "fx_resonance": 254,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 121,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 147,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 6,
                    "lfo_amt": 195,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        2,
                        0,
                        0,
                        1,
                        2,
                        1,
                        2
                    ],
                    "c": [
                        {
                            "n": [
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                157,
                                0,
                                0,
                                0,
                                156,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                157,
                                0,
                                0,
                                0,
                                159,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 255,
                    "osc1_waveform": 2,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 18,
                    "osc2_xenv": 1,
                    "osc2_vol": 191,
                    "osc2_waveform": 2,
                    "noise_fader": 0,
                    "env_attack": 3997,
                    "env_sustain": 56363,
                    "env_release": 100000,
                    "env_master": 255,
                    "fx_filter": 2,
                    "fx_freq": 392,
                    "fx_resonance": 255,
                    "fx_delay_time": 8,
                    "fx_delay_amt": 69,
                    "fx_pan_freq": 5,
                    "fx_pan_amt": 67,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 4,
                    "lfo_amt": 57,
                    "lfo_waveform": 3,
                    "p": [
                        1,
                        2,
                        1,
                        2,
                        1,
                        2,
                        1,
                        2
                    ],
                    "c": [
                        {
                            "n": [
                                130,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                123,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 0,
                    "osc1_waveform": 0,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 0,
                    "osc2_waveform": 0,
                    "noise_fader": 60,
                    "env_attack": 50,
                    "env_sustain": 419,
                    "env_release": 4607,
                    "env_master": 130,
                    "fx_filter": 1,
                    "fx_freq": 10332,
                    "fx_resonance": 120,
                    "fx_delay_time": 4,
                    "fx_delay_amt": 16,
                    "fx_pan_freq": 5,
                    "fx_pan_amt": 108,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 5,
                    "lfo_amt": 187,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        0,
                        0,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                147,
                                147,
                                0,
                                0,
                                147,
                                0,
                                0,
                                147,
                                0,
                                147,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                147,
                                147,
                                0,
                                0,
                                147,
                                0,
                                0,
                                147,
                                0,
                                147
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 1,
                    "osc1_vol": 255,
                    "osc1_waveform": 0,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 1,
                    "osc2_vol": 255,
                    "osc2_waveform": 0,
                    "noise_fader": 0,
                    "env_attack": 50,
                    "env_sustain": 150,
                    "env_release": 4800,
                    "env_master": 200,
                    "fx_filter": 2,
                    "fx_freq": 600,
                    "fx_resonance": 254,
                    "fx_delay_time": 0,
                    "fx_delay_amt": 0,
                    "fx_pan_freq": 0,
                    "fx_pan_amt": 0,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 0,
                    "lfo_freq": 0,
                    "lfo_amt": 0,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        1,
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 255,
                    "osc1_waveform": 2,
                    "osc2_oct": 7,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 154,
                    "osc2_waveform": 2,
                    "noise_fader": 0,
                    "env_attack": 2418,
                    "env_sustain": 1075,
                    "env_release": 10614,
                    "env_master": 240,
                    "fx_filter": 3,
                    "fx_freq": 2962,
                    "fx_resonance": 255,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 117,
                    "fx_pan_freq": 3,
                    "fx_pan_amt": 73,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 5,
                    "lfo_amt": 124,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        0,
                        0,
                        1,
                        2,
                        1,
                        2
                    ],
                    "c": [
                        {
                            "n": [
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                157,
                                0,
                                0,
                                0,
                                156,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                154,
                                0,
                                154,
                                0,
                                152,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                154,
                                0,
                                147,
                                0,
                                152,
                                0,
                                157,
                                0,
                                0,
                                0,
                                159,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 192,
                    "osc1_waveform": 1,
                    "osc2_oct": 6,
                    "osc2_det": 0,
                    "osc2_detune": 9,
                    "osc2_xenv": 0,
                    "osc2_vol": 192,
                    "osc2_waveform": 1,
                    "noise_fader": 0,
                    "env_attack": 137,
                    "env_sustain": 2000,
                    "env_release": 4611,
                    "env_master": 192,
                    "fx_filter": 1,
                    "fx_freq": 982,
                    "fx_resonance": 89,
                    "fx_delay_time": 6,
                    "fx_delay_amt": 25,
                    "fx_pan_freq": 6,
                    "fx_pan_amt": 77,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 3,
                    "lfo_amt": 69,
                    "lfo_waveform": 0,
                    "p": [
                        1,
                        2,
                        1,
                        3,
                        1,
                        3
                    ],
                    "c": [
                        {
                            "n": [
                                130,
                                0,
                                130,
                                0,
                                142,
                                0,
                                130,
                                130,
                                0,
                                142,
                                130,
                                0,
                                142,
                                0,
                                130,
                                0,
                                130,
                                0,
                                130,
                                0,
                                142,
                                0,
                                130,
                                130,
                                0,
                                142,
                                130,
                                0,
                                142,
                                0,
                                130,
                                0
                            ]
                        },
                        {
                            "n": [
                                123,
                                0,
                                123,
                                0,
                                135,
                                0,
                                123,
                                123,
                                0,
                                135,
                                123,
                                0,
                                135,
                                0,
                                123,
                                0,
                                123,
                                0,
                                123,
                                0,
                                135,
                                0,
                                123,
                                123,
                                0,
                                135,
                                123,
                                0,
                                135,
                                0,
                                123,
                                0
                            ]
                        },
                        {
                            "n": [
                                135,
                                0,
                                135,
                                0,
                                147,
                                0,
                                135,
                                135,
                                0,
                                147,
                                135,
                                0,
                                147,
                                0,
                                135,
                                0,
                                135,
                                0,
                                135,
                                0,
                                147,
                                0,
                                135,
                                135,
                                0,
                                147,
                                135,
                                0,
                                147,
                                0,
                                135,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 7,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 255,
                    "osc1_waveform": 3,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 255,
                    "osc2_waveform": 0,
                    "noise_fader": 127,
                    "env_attack": 22,
                    "env_sustain": 88,
                    "env_release": 3997,
                    "env_master": 255,
                    "fx_filter": 3,
                    "fx_freq": 4067,
                    "fx_resonance": 234,
                    "fx_delay_time": 4,
                    "fx_delay_amt": 33,
                    "fx_pan_freq": 2,
                    "fx_pan_amt": 84,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 3,
                    "lfo_amt": 28,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        1,
                        2,
                        1,
                        2,
                        1,
                        3
                    ],
                    "c": [
                        {
                            "n": [
                                0,
                                0,
                                142,
                                0,
                                154,
                                0,
                                0,
                                0,
                                142,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0,
                                0,
                                0,
                                142,
                                0,
                                154,
                                0,
                                0,
                                0,
                                142,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0
                            ]
                        },
                        {
                            "n": [
                                0,
                                0,
                                147,
                                0,
                                154,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                154,
                                0,
                                147,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0,
                                154,
                                0
                            ]
                        },
                        {
                            "n": [
                                0,
                                0,
                                147,
                                0,
                                154,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                154,
                                0,
                                0,
                                0,
                                0,
                                0,
                                147,
                                0,
                                154,
                                0,
                                0,
                                0,
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                },
                {
                    "osc1_oct": 8,
                    "osc1_det": 0,
                    "osc1_detune": 0,
                    "osc1_xenv": 0,
                    "osc1_vol": 0,
                    "osc1_waveform": 0,
                    "osc2_oct": 8,
                    "osc2_det": 0,
                    "osc2_detune": 0,
                    "osc2_xenv": 0,
                    "osc2_vol": 0,
                    "osc2_waveform": 0,
                    "noise_fader": 255,
                    "env_attack": 140347,
                    "env_sustain": 9216,
                    "env_release": 133417,
                    "env_master": 208,
                    "fx_filter": 2,
                    "fx_freq": 2500,
                    "fx_resonance": 16,
                    "fx_delay_time": 2,
                    "fx_delay_amt": 157,
                    "fx_pan_freq": 8,
                    "fx_pan_amt": 207,
                    "lfo_osc1_freq": 0,
                    "lfo_fx_freq": 1,
                    "lfo_freq": 2,
                    "lfo_amt": 51,
                    "lfo_waveform": 0,
                    "p": [
                        0,
                        0,
                        1,
                        1,
                        1,
                        1,
                        1,
                        1
                    ],
                    "c": [
                        {
                            "n": [
                                147,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                            ]
                        }
                    ]
                }
            ],
            "rowLen": 5513,
            "endPattern": 9
        },

        letters: {
            '.' : [
                [,,,,0],
                [,,,,0],
                [,,,,0],
                [,,,,0],
                [,,1,,0]

            ],
            '1': [
                [,1,1,,0],
                [,,1,,0],
                [,,1,,0],
                [,,1,,0],
                [1,1,1,1,1]

            ],
            '2': [
                [1, 1, 1, 1, 0],
                [, , , , 1],
                [, 1, 1, 1, 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            '3': [
                [1, 1, 1, 1, 0],
                [, , , , 1],
                [, 1, 1, 1, 1],
                [, , , , 1],
                [1, 1, 1, 1, 0]
            ],
            '4': [
                [1, , , 1, 0],
                [1, , , 1, 0],
                [1, 1, 1, 1, 1],
                [, , , 1, 0],
                [, , , 1, 0]
            ],
            '5': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, 1, 0],
                [, , , , 1],
                [1, 1, 1, 1, 0]
            ],
            '6': [
                [, 1, 1, 1, 0],
                [1, , , , 0],
                [1, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 0]
            ],
            '7': [
                [1, 1, 1, 1, 1],
                [, , , , 1],
                [, , , 1, 0],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            '8': [
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 0]
            ],
            '9': [
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [, 1, 1, 1, 1],
                [, , , , 1],
                [, 1, 1, 1, 0]
            ],
            '0': [
                [, 1, 1, 1, 0],
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [, 1, 1, 1, 0]
            ],
            'A': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , , , 1]
            ],
            'B': [
                [1, 1, 1, 1, 0],
                [1, , , 1, 0],
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'C': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, , , , 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            'D': [
                [1, 1, 1, , 0],
                [1, , , 1, 0],
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'E': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, , 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            'F': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, , 0],
                [1, , , , 0],
                [1, , , , 0]
            ],
            'G': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, , 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'H': [
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , , , 1]
            ],
            'I': [
                [1, 1, 1, 1, 1],
                [, , 1, , 0],
                [, , 1, , 0],
                [, , 1, , 0],
                [1, 1, 1, 1, 1]
            ],
            'J': [
                [, , , , 1],
                [, , , , 1],
                [, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'K': [
                [1, , , 1, 0],
                [1, , 1, , 0],
                [1, 1, 1, , 0],
                [1, , , 1, 0],
                [1, , , , 1]
            ],
            'L': [
                [1, , , , 0],
                [1, , , , 0],
                [1, , , , 0],
                [1, , , , 0],
                [1, 1, 1, 1, 1]
            ],
            'M': [
                [1, , , , 1],
                [1, 1, , 1, 1],
                [1, , 1, , 1],
                [1, , , , 1],
                [1, , , , 1]
            ],
            'N': [
                [1, , , , 1],
                [1, 1, , , 1],
                [1, , 1, , 1],
                [1, , , 1, 1],
                [1, , , , 1]
            ],
            'O': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'P': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, , , , 0]
            ],
            'Q': [
                [1, 1, 1, 1, 0],
                [1, , , 1, 0],
                [1, , , 1, 0],
                [1, , , 1, 0],
                [1, 1, 1, 1, 1]
            ],
            'R': [
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [1, , , 1, 0],
                [1, , , , 1]
            ],
            'S': [
                [1, 1, 1, 1, 1],
                [1, , , , 0],
                [1, 1, 1, 1, 1],
                [, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'T': [
                [1, 1, 1, 1, 1],
                [, , 1, , 0],
                [, , 1, , 0],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            'U': [
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'V': [
                [1, , , , 1],
                [1, , , , 1],
                [1, , , , 1],
                [, 1, , 1, 0],
                [, , 1, , 0]
            ],
            'W': [
                [1, , , , 1],
                [1, , , , 1],
                [1, , 1, , 1],
                [1, 1, , 1, 1],
                [1, , , , 1]
            ],
            'X': [
                [1, , , , 1],
                [, 1, , 1, 0],
                [, , 1, , 0],
                [, 1, , 1, 0],
                [1, , , , 1]
            ],
            'Y': [
                [1, , , , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            'Z': [
                [1, 1, 1, 1, 1],
                [, , , 1, 0],
                [, , 1, , 0],
                [, 1, , , 0],
                [1, 1, 1, 1, 1]
            ],
            ' ': [
                [, , , , 0],
                [, , , , 0],
                [, , , , 0],
                [, , , , 0],
                [, , , , 0]
            ],
            ',': [
                [, , , , 0],
                [, , , , 0],
                [, , , , 0],
                [, , 1, , 0],
                [, , 1, , 0]
            ],
            '+': [
                [, , , , 0],
                [, , 1, , 0],
                [, 1, 1, 1, 0],
                [, , 1, , 0],
                [, , , , 0]
            ],
            '/': [
                [, , , , 1],
                [, , , 1, 0],
                [, , 1, , 0],
                [, 1, , , 0],
                [1, , , , 0]
            ],
            ':': [
                [, , , , 0],
                [, , 1, , 0],
                [, , , , 0],
                [, , 1, , 0],
                [, , , , 0]
            ],
            '@': [
                [1, 1, 1, 1, 1],
                [, , , , 1],
                [1, 1, 1, , 1],
                [1, , 1, , 1],
                [1, 1, 1, 1, 1]
            ],
            'x': [ //solid first checkers
                [1, , 1, , 1],
                [, 1, , 1, 0],
                [1, , 1, , 1],
                [, 1, , 1, 0],
                [1, , 1, , 1]
            ],
            'z': [
                //empty first checkers
                [, 1, , 1, 0],
                [1, , 1, , 1],
                [, 1, , 1, 0],
                [1, , 1, , 1],
                [, 1, , 1, 0]
            ],
            'o': [
                //box with dot
                [1, 1, 1, 1, 1],
                [1, , , , 1],
                [1, , 1, , 1],
                [1, , , , 1],
                [1, 1, 1, 1, 1]
            ],
            'e': [
                //down-right slope
                [1,,,,0],
                [1,1,,,0],
                [1,1,1,,0],
                [1,1,1,1,0],
                [1,1,1,1,1],

            ],
            'w': [
                //down-left slope
                [,,,,1],
                [,,,1,1],
                [,,1,1,1],
                [,1,1,1,1],
                [1,1,1,1,1],

            ],
            's': [
                //up-left slope
                [1, 1, 1, 1, 1],
                [, 1, 1, 1, 1],
                [, , 1, 1, 1],
                [, , , 1, 1],
                [, , , , 1]
            ],
            'd': [
                //up-right slope
                [1,1,1,1,1],
                [1,1,1,1,0],
                [1,1,1,,0],
                [1,1,,,0],
                [1,,,,0]

            ]

        }

    };

    return g;

}(GAME));
